Fix shepherd not working after error during computation
mild-blue/isletnet-shepherd pull request #8
Opened 2024-01-05 23:07 UTC by jakubmonhart

2024-01-07 10:41 UTC, kubantjan commented
@jakubmonhart  prosim vysvetli tady (jako se dela na SLP co teda opravujes)

2024-01-07 10:42 UTC, kubantjan requested changes
Chybi vysvetlivky

2024-01-24 17:13 UTC, curdopet approved these changes

2024-01-24 20:43 UTC, kubantjan approved these changes

2024-01-31 20:07 UTC, merged